Repository AY2021S1-CS2103T-W15-3/tp, pull requests merged in 2020-10, with the labels that each got.

#47 find NRIC command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/patient/KeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/HospifyParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/patient/KeywordsPredicateTest.java
Labels: priority.High, type.Task

#48 delete NRIC command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/patient/Nric.java
Labels: priority.High, type.Task

#49 Update AboutUs
  docs/AboutUs.md
  docs/team/gabrielteo.md
Labels: type.Task

#50 Add base colors
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Task

#51 update AboutUs
  docs/team/gabrielteo.md
Labels: type.Task

#53 Update Find functionality and more
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/patient/KeywordsPredicate.java
  src/main/java/seedu/address/model/patient/Nric.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/patient/KeywordsPredicateTest.java
  src/test/java/seedu/address/model/patient/NricTest.java
Labels: type.Task

#62 Add test cases for count command
  src/test/java/seedu/address/logic/commands/CountCommandTest.java
Labels: type.Task

#68 edit help command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/patient/Nric.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/patient/KeywordsPredicateTest.java
  src/test/java/seedu/address/model/patient/NricTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#69 Fix Ui bug
  src/main/resources/view/Extensions.css
Labels: bug severity.High

#70 update App window heading and bottom path display
  preferences.json
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Task

#71 Update docs
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/Ui_old.png
  docs/images/findAlexDavidResult.png
  docs/images/findAlexDavidResult_old.png
  docs/images/findbernices0000003aResult.png
  docs/images/helpMessage.png
  docs/images/helpMessage_old.png
  docs/team/gabrielteo.md
  preferences.json
  src/main/java/seedu/address/model/patient/Nric.java
Labels: type.Task

#73 fix minor UG formatting
  docs/UserGuide.md
Labels: type.Task

#75 Branch adapt gui
  src/main/java/seedu/address/logic/commands/CountCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/CommandDescription.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/Hospify.css
Labels: priority.High

#76 Update command desc and help display
  docs/UserGuide.md
  docs/index.md
  docs/team/gabrielteo.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: type.Task

#77 Update docs
  docs/images/helpMessage.png
Labels: type.Task

#80 Add Appointment Class
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/model/patient/Patient.java
Labels: priority.High, type.Task

#87 Class Appointment
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/model/patient/Nric.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Task

#85 Appointment command
  src/main/java/seedu/address/logic/commands/AppointmentCommand/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/AppointmentCommand/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/HospifyParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, type.Task

#90 Branch adapt gui
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/Hospify.css
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Medium

#91 Appointment bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
Labels: bug severity.Medium, priority.High

#94 Refactor Hospify and update DG
  build.gradle
  docs/DeveloperGuide.md
  docs/team/gabrielteo.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/patient/Address.java
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/model/patient/Name.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonSerializableHospify.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.Medium, type.Task

#96 Add Medical Record functionality and test cases
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AppointmentCommand/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/MedicalRecord.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/PatientListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/patient/MedicalRecordTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#98 Fix Checkstyle Errors
  src/main/java/seedu/address/logic/commands/AppointmentCommand/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/DeleteApptCommand.java
  src/main/java/seedu/address/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/address/logic/parser/HospifyParser.java
  src/main/resources/view/PatientListCard.fxml
Labels: priority.Low, type.Task

#99 Add assertion statement
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: priority.Low

#104 Solve minor assertion error
  .gitignore
  preferences.json
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/AddApptCommand.java
  src/main/java/seedu/address/logic/parser/AddApptCommandParser.java
Labels: priority.Low

#115 add duplicate appointment exception
  src/main/java/seedu/address/logic/commands/appointmentcommand/AddApptCommand.java
Labels: type.Task

#116 Class appointment
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/EditApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/ShowApptCommand.java
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/model/patient/MedicalRecord.java
  src/main/java/seedu/address/model/patient/Name.java
  src/main/java/seedu/address/model/patient/Nric.java
  src/main/java/seedu/address/model/patient/Phone.java
Labels: type.Task

#119 Branch show appointment
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/AppointmentWindow.fxml
  src/main/resources/view/Hospify.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListCard.fxml
Labels: type.Task

#121 trial JAR release
  docs/team/gabrielteo.md
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#122 Update JAR link
  docs/UserGuide.md
Labels: type.Task

#124 App heading and bottom
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/HospifyBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyHospifyBook.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/HospifyStorage.java
  src/main/java/seedu/address/storage/JsonHospifyStorage.java
  src/main/java/seedu/address/storage/JsonSerializableHospify.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPatientHospify.json
  src/test/data/JsonAddressBookStorageTest/invalidPatientHospify.json
  src/test/data/JsonAddressBookStorageTest/notJsonFormatHospify.json
  src/test/data/JsonSerializableHospifyTest/duplicatePatientHospify.json
  src/test/data/JsonSerializableHospifyTest/invalidPatientHospify.json
  src/test/data/JsonSerializableHospifyTest/typicalPatientsHospify.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CountCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/model/patient/UniquePatientListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/storage/JsonHospifyStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableHospifyTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: bug severity.Medium

#132 Fix add appt bug
  src/main/java/seedu/address/logic/parser/AddApptCommandParser.java
  src/main/java/seedu/address/model/patient/Appointment.java
Labels: bug severity.Low

#135 Fix visual bug with showAppt
  src/main/java/seedu/address/ui/AppointmentWindow.java
Labels: bug severity.High

#138 Change number of appointments to upcoming appointments
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/PatientListCard.fxml
Labels: type.Enhancement

#140 Addappt error message(system time)
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Appointment.java
Labels: bug severity.Medium, type.Task

#141 Update docs
  docs/DeveloperGuide.md
  docs/team/gabrielteo.md
Labels: type.Task

#144 Fix NRIC bug
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/HospifyBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: bug severity.High

#148 Update User Guide
  docs/UserGuide.md
  docs/images/Add patient.PNG
  docs/images/Help window.PNG
  docs/images/Hospify download page.png
  docs/images/Medical record example (1).png
  docs/images/Medical record example (2).png
  docs/images/Medical record example (3).png
  docs/images/Medical record example (4).png
  docs/images/Ui.png
Labels: priority.Medium, type.Task

#151 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram(MR).puml
  docs/diagrams/MedicalRecordActivityDiagram.puml
  docs/images/UML_Diagrams/AddSequenceDiagramMR.png
  docs/images/UML_Diagrams/MedicalRecordActivityDiagram.png
Labels: priority.Medium, type.Task

#152 Update Developer Guide
  docs/DeveloperGuide.md
  docs/images/UML_Diagrams/MedicalRecordActivityDiagram.png
Labels: priority.Medium, type.Task

#155 Add description in appt commands
  src/main/java/seedu/address/logic/commands/appointmentcommand/AddApptCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/JsonSerializableHospify.java
Labels: priority.Medium, type.Task

#157 Update docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/findbernices0000003aResult.png
  docs/team/gabrielteo.md
Labels: type.Task

#158 Class appointment
  docs/team/gabrielteo.md
  src/main/java/seedu/address/logic/commands/appointmentcommand/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/EditApptCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditApptCommandParser.java
Labels: bug severity.High, priority.High, type.Bug

#163 Update Help Window, Appointment Window
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/ui/AppointmentDescription.java
  src/main/java/seedu/address/ui/AppointmentWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/AppointmentWindow.fxml
  src/main/resources/view/PatientListCard.fxml
Labels: priority.High

#166 Fix editAppt bugs
  src/main/java/seedu/address/logic/commands/appointmentcommand/EditApptCommand.java
Labels: bug severity.Medium

#167 Use nric in appt commands
  src/main/java/seedu/address/logic/commands/appointmentcommand/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/EditApptCommand.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser/AddApptCommandParser.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser/DeleteApptCommandParser.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser/EditApptCommandParser.java
  src/main/java/seedu/address/logic/parser/AppointmentCommandParser/ShowApptCommandParser.java
  src/main/java/seedu/address/logic/parser/HospifyParser.java
Labels: priority.High, type.Task

#169 Update docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/deleteDavidResult.png
  docs/images/deleteOliveiroResult.png
  docs/images/deleteTwoResult.png
  docs/images/findOliveiro.png
  docs/images/listResult.png
Labels: priority.Medium, type.Task

#170 Update docs
  docs/UserGuide.md
  docs/images/addAppt.png
  docs/images/deleteAppt.png
  docs/images/editAppt.png
  docs/images/findAlexDavidResult.png
  docs/images/findbernices0000003aResult.png
  docs/team/gabrielteo.md
  src/main/java/seedu/address/logic/commands/appointmentcommand/AddApptCommand.java
Labels: type.Task

#171 Bug fixes
  docs/UserGuide.md
Labels: type.Bug

#173 Jar release
  docs/team/gabrielteo.md
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#175 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ShowApptCliSequenceDiagram.puml
  docs/diagrams/ShowApptDiagram.puml
  docs/diagrams/showApptGuiSequenceDiagram.puml
  docs/images/UML_Diagrams/ShowApptDiagram.png
  docs/images/cleanHelpWindow.PNG
  docs/images/showAppt/ShowApptActivityDiagram.png
  docs/images/showAppt/ShowApptCliSequenceDiagram.png
  docs/images/showAppt/ShowApptGuiSequenceDiagram.png
Labels: priority.High

#221 update appointment testcases
  src/main/java/seedu/address/logic/commands/appointmentcommand/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/EditApptCommand.java
  src/main/java/seedu/address/logic/parser/HospifyParser.java
  src/main/java/seedu/address/logic/parser/appointmentCommandParser/AddApptCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentCommandParser/DeleteApptCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentCommandParser/EditApptCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentCommandParser/ShowApptCommandParser.java
  src/main/java/seedu/address/model/patient/Appointment.java
  src/test/java/seedu/address/logic/commands/appointmentCommandTest/AddApptCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentCommandTest/DeleteApptCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentCommandTest/EditApptCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentCommandTest/ShowApptCommandTest.java
  src/test/java/seedu/address/model/patient/AppointmentTest.java
Labels: priority.Medium, type.Task

#224 Update regex for MR URL and Phone
  src/main/java/seedu/address/model/patient/MedicalRecord.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/patient/KeywordsPredicateTest.java
Labels: bug severity.Medium
