Repository AY2021S1-CS2103T-W15-3/tp, pull requests merged in 2020-11, with the labels that each got.

#226 PE-D review bug fixes
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CountCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/HospifyBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/model/patient/MedicalRecord.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CountCommandTest.java
  src/test/java/seedu/address/model/patient/EmailTest.java
Labels: bug severity.High, priority.High, type.Bug

#227 Update User Guide (based on UG consultation and PE-D reviews)
  docs/UserGuide.md
  docs/images/list1.png
  docs/images/list2.png
Labels: bug severity.Low, priority.Medium, type.Task

#243 Update Hospify v1.4
  docs/team/todoge.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/ShowMrCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/ShowApptCommand.java
  src/main/java/seedu/address/logic/parser/HospifyParser.java
  src/main/java/seedu/address/logic/parser/ShowMrParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/AppointmentDescription.java
  src/main/java/seedu/address/ui/AppointmentWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/AppointmentWindow.fxml
  src/main/resources/view/Hospify.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientListCard.fxml
Labels: bug severity.Medium

#245 Made email not a compulsory field
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/patient/EmailTest.java
Labels: priority.High

#246 Fix bugs and improve UI
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/allergy/Allergy.java
  src/main/java/seedu/address/model/patient/Address.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/model/patient/Name.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/Phone.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientCard.java
Labels: type.Bug

#250 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/UML_Diagrams/FindSequenceDiagram.png
  docs/images/editPatient.png
  docs/team/ringo1225.md
Labels: type.Task

#251 solve picture bug
  docs/UserGuide.md
Labels: type.Task

#252 Update images in UG
  docs/UserGuide.md
  docs/images/CountExample.PNG
  docs/images/SortFind.PNG
  docs/images/SortFind2.PNG
  docs/images/SortName.PNG
  docs/images/SortNric.PNG
Labels: bug severity.Low, priority.High

#253 Class appointment
  docs/team/gabrielteo.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/appointmentCommandParser/AddApptCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentCommandParser/DeleteApptCommandParser.java
  src/main/java/seedu/address/logic/parser/appointmentCommandParser/EditApptCommandParser.java
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/test/java/seedu/address/model/patient/AppointmentTest.java
Labels: bug severity.Medium, priority.High

#254 Fix http bug
  src/main/java/seedu/address/logic/commands/ShowMrCommand.java
Labels: bug severity.High

#269 Help command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CountCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ShowMrCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/AddApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/DeleteApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/EditApptCommand.java
  src/main/java/seedu/address/logic/commands/appointmentcommand/ShowApptCommand.java
  src/main/java/seedu/address/model/patient/Appointment.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, type.Task

#271 update UG screenshots
  docs/UserGuide.md
  docs/images/addAppt.png
  docs/images/deleteAppt.png
  docs/images/editAppt.png
  docs/images/findAlexDavidResult.png
  docs/images/findbernices0000003aResult.png
  docs/team/gabrielteo.md
  src/main/java/seedu/address/model/patient/Appointment.java
Labels: type.Task

#276 last edit of docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ringo1225.md
Labels: priority.Medium

#279 Update developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AppointmentActivityDiagram.puml
  docs/images/UML_Diagrams/AppointmentActivityDiagram.png
  docs/team/gabrielteo.md
Labels: type.Task

#283 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddAppointmentSequenceDiagram.puml
  docs/diagrams/AppointmentActivityDiagram.puml
  docs/images/UML_Diagrams/AddAppointmentSequenceDiagram.png
  docs/images/UML_Diagrams/AppointmentActivityDiagram.png
  docs/team/gabrielteo.md
Labels: type.Task

#288 Class appointment
  src/test/java/seedu/address/logic/commands/appointmentCommandTest/AddApptCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentCommandTest/DeleteApptCommandTest.java
  src/test/java/seedu/address/logic/commands/appointmentCommandTest/EditApptCommandTest.java
Labels: type.Task

#290 Jar release
  docs/team/gabrielteo.md
  src/main/java/seedu/address/MainApp.java
Labels: type.Task
