Repository AY2021S1-CS2103T-W15-3/tp, pull requests merged in 2020-09, with the labels that each got.

#20 Update AboutUs
  docs/AboutUs.md
  docs/images/gabrielteo.png
  docs/team/gabrielteo.md
Labels: priority.Medium, type.Task

#21 update Developer Guide and fix typos in README
  README.md
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#36 handle DuplicateNricException
  src/main/java/seedu/address/model/patient/UniquePersonList.java
  src/main/java/seedu/address/model/patient/exceptions/DuplicateNricException.java
Labels: type.Task

#39 Branch docs
  docs/UserGuide.md
  docs/_config.yml
Labels: priority.Medium, type.Task
